import { notFound } from "next/navigation"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { supabaseAdmin } from "@/lib/supabase"
import SavingsHero from "@/components/results/SavingsHero"
import RecommendationRow from "@/components/results/RecommendationRow"
import CTABlock from "@/components/results/CTABlock"
import { ToolRecommendation } from "@/lib/types"

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { data, error } = await supabaseAdmin
    .from("audits")
    .select("total_monthly_savings")
    .eq("id", id)
    .single()

  const savings = !error && data ? data.total_monthly_savings : 0

  return {
    title: `AI Spend Audit — $${savings} saved`,
    description: "See how this startup identified wasted AI tool spend with StackAudit.",
    openGraph: {
      title: `This startup could save $${savings}/month on AI tools`,
      description: "Run your own free audit at stackaudit.app",
    },
  }
}

export default async function SharedAuditPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { data, error } = await supabaseAdmin
    .from("audits")
    .select("*")
    .eq("id", id)
    .single()

  if (error || !data) return notFound()

  const recommendations = data.savings_json || []
  const totalMonthlySavings = recommendations.reduce(
    (sum: number, r: ToolRecommendation) => sum + (r.monthlySavings ?? 0), 0
  )
  const totalAnnualSavings = recommendations.reduce(
    (sum: number, r: ToolRecommendation) => sum + (r.annualSavings ?? 0), 0
  )
  void totalAnnualSavings

  return (
    <div className="min-h-screen bg-background">
      <main className="max-w-[680px] mx-auto px-4 py-8">
        <div className="flex items-center justify-between mb-6">
          <Link
            href="/audit"
            className="inline-flex items-center gap-2 text-sm text-on-surface-variant hover:text-primary transition-colors"
          >
            <ArrowLeft className="w-4 h-4" /> Run your own audit
          </Link>
          <span className="text-xs font-mono text-on-surface-variant bg-surface-container px-3 py-1 rounded">
            Shared Audit
          </span>
        </div>

        <SavingsHero amount={totalMonthlySavings} />

        <div className="border-t border-outline-variant/30 mt-6">
          {recommendations.map((rec: ToolRecommendation, i: number) => (
            <RecommendationRow key={i} rec={rec} />
          ))}
        </div>

        <CTABlock savings={totalMonthlySavings} />

        <div className="mt-12 text-center">
          <p className="text-on-surface-variant text-sm mb-3">
            This audit was generated by StackAudit
          </p>
          <Link
            href="/audit"
            className="bg-primary-container text-on-primary-container font-bold px-6 py-3 rounded hover:brightness-110 transition-all"
          >
            Run Your Free Audit →
          </Link>
        </div>
      </main>
    </div>
  )
}
