import { notFound } from "next/navigation"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { supabaseAdmin } from "@/lib/supabase"
import SavingsHero from "@/components/results/SavingsHero"
import RecommendationRow from "@/components/results/RecommendationRow"
import CTABlock from "@/components/results/CTABlock"
import { ToolRecommendation } from "@/lib/types"

const BASE = "https://stack-audit-ashy.vercel.app"

// Recompute savings from recommendation rows — never trust the stored aggregate
function computeSavings(savingsJson: unknown): number {
  if (!Array.isArray(savingsJson)) return 0
  return savingsJson.reduce(
    (sum: number, r: { monthlySavings?: number }) =>
      sum + (r.monthlySavings ?? 0),
    0
  )
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const { data, error } = await supabaseAdmin
    .from("audits")
    .select("savings_json, total_monthly_savings")
    .eq("id", id)
    .single()

  if (error || !data) {
    return {
      title: "AI Spend Audit Results",
      description:
        "See how startups identify wasted AI tool spend with StackAudit. Free audit, no login.",
    }
  }

  const savings =
    computeSavings(data.savings_json) || data.total_monthly_savings || 0

  return {
    title: `AI Spend Audit — $${savings.toLocaleString()}/mo in savings found`,
    description: `This team found $${savings.toLocaleString()}/month in wasted AI tool spend. Run your own free audit at StackAudit — no login required.`,
    openGraph: {
      title: `This team could save $${savings.toLocaleString()}/month on AI tools`,
      description:
        "Run your own free AI spend audit at StackAudit. No login required.",
      url: `${BASE}/audit/${id}`,
      type: "website",
    },
    twitter: {
      card: "summary",
      title: `$${savings.toLocaleString()}/mo in AI tool savings found`,
      description: "Run your free audit at StackAudit.",
    },
    alternates: {
      canonical: `${BASE}/audit/${id}`,
    },
  }
}

export default async function SharedAuditPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const { data, error } = await supabaseAdmin
    .from("audits")
    .select("*")
    .eq("id", id)
    .single()

  if (error || !data) return notFound()

  const recommendations: ToolRecommendation[] = Array.isArray(data.savings_json)
    ? data.savings_json
    : []

  // Recompute from rows — stored aggregate may be stale
  const totalMonthlySavings =
    computeSavings(data.savings_json) || data.total_monthly_savings || 0
  const totalAnnualSavings = totalMonthlySavings * 12

  return (
    <div className="min-h-screen bg-background">
      <main className="max-w-[680px] mx-auto px-4 py-8" id="main-content">
        <div className="flex items-center justify-between mb-6">
          <Link
            href="/audit"
            className="inline-flex items-center gap-2 text-sm text-on-surface-variant hover:text-primary transition-colors"
          >
            <ArrowLeft className="w-4 h-4" /> Run your own audit
          </Link>
          <span className="text-xs font-mono text-on-surface-variant bg-surface-container px-3 py-1 rounded">
            Shared Audit
          </span>
        </div>

        <SavingsHero amount={totalMonthlySavings} />

        <div className="border-t border-outline-variant/30 mt-6">
          {recommendations.map((rec, i) => (
            <RecommendationRow key={i} rec={rec} />
          ))}
        </div>

        <CTABlock savings={totalMonthlySavings} />

        {/* Internal link back to homepage — important for SEO crawlability */}
        <div className="mt-12 text-center">
          <p className="text-on-surface-variant text-sm mb-3">
            Audit generated by{" "}
            <Link href="/" className="text-primary hover:underline">
              StackAudit
            </Link>
            {" "}· Potential annual savings:{" "}
            <span className="text-primary font-bold">
              ${totalAnnualSavings.toLocaleString()}/yr
            </span>
          </p>
          <Link
            href="/audit"
            className="bg-primary-container text-on-primary-container font-bold px-6 py-3 rounded hover:brightness-110 transition-all"
          >
            Run Your Free Audit →
          </Link>
        </div>
      </main>
    </div>
  )
}
