import { NextResponse } from "next/server"
import { Resend } from "resend"
import { supabaseAdmin } from "@/lib/supabase"
import { AuditResult, ToolRecommendation } from "@/lib/types"

const resend = new Resend(process.env.RESEND_API_KEY)

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n)
}

function buildEmailHtml(email: string, auditData: AuditResult | null): string {
  const monthly = auditData ? formatCurrency(auditData.totalMonthlySavings) : "—"
  const annual = auditData ? formatCurrency(auditData.totalAnnualSavings) : "—"
  const shareUrl = auditData
    ? `https://stack-audit-ashy.vercel.app/audit/${auditData.shareSlug}`
    : "https://stack-audit-ashy.vercel.app"

  const rows = auditData?.recommendations ?? []

  const tableRows = rows
    .map(
      (r: ToolRecommendation) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #3c4947;">${r.tool}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #3c4947;">${r.currentPlan}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #3c4947;">${r.recommendedAction}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #3c4947;color:#4fdbc8;font-weight:bold;">+${formatCurrency(r.monthlySavings)}/mo</td>
      </tr>`
    )
    .join("")

  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8" /><title>Your StackAudit Report</title></head>
<body style="margin:0;padding:0;background:#0e1513;font-family:system-ui,-apple-system,sans-serif;color:#dde4e1;">
  <div style="max-width:600px;margin:40px auto;padding:0 20px;">

    <!-- Header -->
    <div style="margin-bottom:32px;">
      <p style="font-family:monospace;font-size:20px;font-weight:700;color:#4fdbc8;margin:0 0 4px;">StackAudit</p>
      <p style="color:#bbcac6;margin:0;font-size:14px;">Your personalized AI spend report</p>
    </div>

    <!-- Savings hero -->
    <div style="background:#1a211f;border:1px solid #3c4947;border-radius:12px;padding:32px;text-align:center;margin-bottom:32px;">
      <p style="font-family:monospace;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;color:#4fdbc8;margin:0 0 8px;">Total Potential Savings</p>
      <p style="font-size:48px;font-weight:700;color:#4fdbc8;margin:0 0 4px;">${monthly}<span style="font-size:24px;">/mo</span></p>
      <p style="color:#bbcac6;margin:0;">${annual} per year</p>
    </div>

    <!-- Recommendations table -->
    ${rows.length > 0 ? `
    <div style="margin-bottom:32px;">
      <p style="font-family:monospace;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;color:#4fdbc8;margin:0 0 12px;">Recommendations</p>
      <table style="width:100%;border-collapse:collapse;background:#1a211f;border:1px solid #3c4947;border-radius:8px;overflow:hidden;">
        <thead>
          <tr style="background:#252b2a;">
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#bbcac6;font-weight:600;">Tool</th>
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#bbcac6;font-weight:600;">Current Plan</th>
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#bbcac6;font-weight:600;">Action</th>
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#bbcac6;font-weight:600;">Savings</th>
          </tr>
        </thead>
        <tbody>${tableRows}</tbody>
      </table>
    </div>
    ` : ""}

    <!-- AI Analysis -->
    ${auditData?.aiAnalysis ? `
    <div style="margin-bottom:32px;">
      <p style="font-family:monospace;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;color:#4fdbc8;margin:0 0 12px;">✦ AI Analysis</p>
      <div style="background:#1a211f;border-left:3px solid #859490;border-radius:0 8px 8px 0;padding:16px;">
        <p style="color:#dde4e1;line-height:1.6;margin:0;">${auditData.aiAnalysis}</p>
      </div>
    </div>
    ` : ""}

    <!-- Share link -->
    <div style="background:#1a211f;border:1px solid #3c4947;border-radius:8px;padding:16px;margin-bottom:32px;">
      <p style="font-size:12px;color:#bbcac6;margin:0 0 8px;">Your shareable audit link:</p>
      <a href="${shareUrl}" style="color:#4fdbc8;font-family:monospace;font-size:13px;word-break:break-all;">${shareUrl}</a>
    </div>

    <!-- Footer -->
    <div style="border-top:1px solid #3c4947;padding-top:20px;text-align:center;">
      <p style="font-size:12px;color:#bbcac6;margin:0;">
        This report was generated by <strong>StackAudit</strong> — 
        <a href="https://stack-audit-ashy.vercel.app" style="color:#4fdbc8;">stack-audit-ashy.vercel.app</a>
      </p>
    </div>
  </div>
</body>
</html>
`
}

export async function POST(request: Request) {
  try {
    const { email, company, role, website, auditData } = await request.json()

    // Honeypot — bots fill hidden fields
    if (website) {
      return NextResponse.json({ success: true })
    }

    if (!email) {
      return NextResponse.json({ error: "Email required" }, { status: 400 })
    }

    // Save lead to Supabase
    const { error: dbError } = await supabaseAdmin
      .from("leads")
      .insert({ email, company_name: company, role })

    if (dbError) {
      console.error("Supabase error:", dbError)
    }

    // Send email via Resend — best effort, don't block response
    try {
      const html = buildEmailHtml(email, auditData ?? null)
      await resend.emails.send({
        from: "StackAudit <onboarding@resend.dev>",
        to: email,
        subject: "Your StackAudit Report",
        html,
      })
    } catch (emailError) {
      console.error("Resend error:", emailError)
    }

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error(error)
    return NextResponse.json({ error: "Failed to save" }, { status: 500 })
  }
}